### ISSUE TITLE
April's meetup

### ISSUE THREAD

**Issue by nerdyvaishali** [Diversifyingopensource/diversifyingopensource.github.io#7]
**Date:** April 7, 2018 
**Time:** 2pm to 6pm
**Venue:** Red Hat India Pvt Ltd, Bangalore
**Tentative Agenda:**

2:00 pm: Welcome and introductions

2:10 pm: Introduction of mentors and groups

2:30 pm: Talk Idea generation

3:00 pm: Talk abstract generation

3:30 pm: Coffee break

3:45 pm: Talk proposal writing and feedback with mentors

4:30 pm: What makes a good bio?

5:00 pm: Panel

5:30 pm: Networking and feedback

**Comment by fatimarafiqui** [comment]
@nerdyvaishali It would be great if we could have the recordings of the talk/sessions (if possible) on youtube or somewhere. People who are not located in Bangalore can also be a part of it which might benefit the community as a whole.

**Comment by nikhita** [comment]
> @nerdyvaishali It would be great if we could have the recordings of the talk/sessions (if possible) on youtube or somewhere. People who are not located in Bangalore can also be a part of it which might benefit the community as a whole.

+1. Also, the theme for this meetup looks super interesting! Are any meeting notes (ahem, meetup notes :slightly_smiling_face: ) available?

Side note -- should this issue an https://github.com/Diversifyingopensource/diversifyingopensource.github.io/issues/8 be closed? Looks like the meetup is over. :)

**Comment by nerdyvaishali** [comment]
Hi, @fatimarafiqui and @nikhita ! Thanks for reviving this issue. Unfortunately, this meetup didn't happen because of several reasons. But if there is an enough interest and if someone wants to organize this sort of online meetup then I would be happy to participate and help. I'll close the issue as well.

**Comment by nikhita** [comment]
> But if there is an enough interest and if someone wants to organize this sort of online meetup then I would be happy to participate and help.

I would be glad to collaborate on an online meetup for this! Should I create a new issue for it?

**Comment by nikhita** [comment]
> I would be glad to collaborate on an online meetup for this! Should I create a new issue for it?

Spoke with @nerdyvaishali and created #9.
